services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,dynamodb,iam,lambda,cloudwatch,logs
      - DEFAULT_REGION=eu-central-1
      - LAMBDA_EXECUTOR=docker-reuse
      - DEBUG=1
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  terraform:
    image: hashicorp/terraform:1.8.4
    container_name: terraform
    working_dir: /workspace
    volumes:
      - ./terraform:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-central-1
    # keep the container alive so you can exec into it for interactive work
    entrypoint: ["sh", "-c", "tail -f /dev/null || sleep infinity"]
    tty: true
    stdin_open: true
    restart: unless-stopped
    depends_on:
      - localstack